// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: websocket/websocket.proto

package websocket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId   string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content          string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Nonce            string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TagElement       string                 `protobuf:"bytes,5,opt,name=tag_element,json=tagElement,proto3" json:"tag_element,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReplyToElementId *string                `protobuf:"bytes,7,opt,name=reply_to_element_id,json=replyToElementId,proto3,oneof" json:"reply_to_element_id,omitempty"`
	VuesMessage      int32                  `protobuf:"varint,8,opt,name=vues_message,json=vuesMessage,proto3" json:"vues_message,omitempty"`
	Lien             *string                `protobuf:"bytes,9,opt,name=lien,proto3,oneof" json:"lien,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_websocket_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *SendMessageRequest) GetTagElement() string {
	if x != nil {
		return x.TagElement
	}
	return ""
}

func (x *SendMessageRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SendMessageRequest) GetReplyToElementId() string {
	if x != nil && x.ReplyToElementId != nil {
		return *x.ReplyToElementId
	}
	return ""
}

func (x *SendMessageRequest) GetVuesMessage() int32 {
	if x != nil {
		return x.VuesMessage
	}
	return 0
}

func (x *SendMessageRequest) GetLien() string {
	if x != nil && x.Lien != nil {
		return *x.Lien
	}
	return ""
}

type SendMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_websocket_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_websocket_websocket_proto protoreflect.FileDescriptor

const file_websocket_websocket_proto_rawDesc = "" +
	"\n" +
	"\x19websocket/websocket.proto\x12\twebsocket\"\xce\x02\n" +
	"\x12SendMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\x12\x1f\n" +
	"\vtag_element\x18\x05 \x01(\tR\n" +
	"tagElement\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x122\n" +
	"\x13reply_to_element_id\x18\a \x01(\tH\x00R\x10replyToElementId\x88\x01\x01\x12!\n" +
	"\fvues_message\x18\b \x01(\x05R\vvuesMessage\x12\x17\n" +
	"\x04lien\x18\t \x01(\tH\x01R\x04lien\x88\x01\x01B\x16\n" +
	"\x14_reply_to_element_idB\a\n" +
	"\x05_lien\"*\n" +
	"\x10SendMessageReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\\\n" +
	"\x0fMessageReceiver\x12I\n" +
	"\vSendMessage\x12\x1d.websocket.SendMessageRequest\x1a\x1b.websocket.SendMessageReplyB5Z3conversation-global-ctn/message-ctn/proto;websocketb\x06proto3"

var (
	file_websocket_websocket_proto_rawDescOnce sync.Once
	file_websocket_websocket_proto_rawDescData []byte
)

func file_websocket_websocket_proto_rawDescGZIP() []byte {
	file_websocket_websocket_proto_rawDescOnce.Do(func() {
		file_websocket_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocket_websocket_proto_rawDesc), len(file_websocket_websocket_proto_rawDesc)))
	})
	return file_websocket_websocket_proto_rawDescData
}

var file_websocket_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_websocket_websocket_proto_goTypes = []any{
	(*SendMessageRequest)(nil), // 0: websocket.SendMessageRequest
	(*SendMessageReply)(nil),   // 1: websocket.SendMessageReply
}
var file_websocket_websocket_proto_depIdxs = []int32{
	0, // 0: websocket.MessageReceiver.SendMessage:input_type -> websocket.SendMessageRequest
	1, // 1: websocket.MessageReceiver.SendMessage:output_type -> websocket.SendMessageReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_websocket_websocket_proto_init() }
func file_websocket_websocket_proto_init() {
	if File_websocket_websocket_proto != nil {
		return
	}
	file_websocket_websocket_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocket_websocket_proto_rawDesc), len(file_websocket_websocket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_websocket_websocket_proto_goTypes,
		DependencyIndexes: file_websocket_websocket_proto_depIdxs,
		MessageInfos:      file_websocket_websocket_proto_msgTypes,
	}.Build()
	File_websocket_websocket_proto = out.File
	file_websocket_websocket_proto_goTypes = nil
	file_websocket_websocket_proto_depIdxs = nil
}
