// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rag/analyseIa.proto

package rag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageIa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageIa) Reset() {
	*x = MessageIa{}
	mi := &file_rag_analyseIa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageIa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageIa) ProtoMessage() {}

func (x *MessageIa) ProtoReflect() protoreflect.Message {
	mi := &file_rag_analyseIa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageIa.ProtoReflect.Descriptor instead.
func (*MessageIa) Descriptor() ([]byte, []int) {
	return file_rag_analyseIa_proto_rawDescGZIP(), []int{0}
}

func (x *MessageIa) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageIa) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TypePourcentage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Pourcentage   int32                  `protobuf:"varint,2,opt,name=pourcentage,proto3" json:"pourcentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypePourcentage) Reset() {
	*x = TypePourcentage{}
	mi := &file_rag_analyseIa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypePourcentage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypePourcentage) ProtoMessage() {}

func (x *TypePourcentage) ProtoReflect() protoreflect.Message {
	mi := &file_rag_analyseIa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypePourcentage.ProtoReflect.Descriptor instead.
func (*TypePourcentage) Descriptor() ([]byte, []int) {
	return file_rag_analyseIa_proto_rawDescGZIP(), []int{1}
}

func (x *TypePourcentage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TypePourcentage) GetPourcentage() int32 {
	if x != nil {
		return x.Pourcentage
	}
	return 0
}

type MessageIaReponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SousEntendu            bool                   `protobuf:"varint,2,opt,name=sousEntendu,proto3" json:"sousEntendu,omitempty"`
	PourcentageSousEntendu int32                  `protobuf:"varint,3,opt,name=pourcentageSousEntendu,proto3" json:"pourcentageSousEntendu,omitempty"`
	Types                  []*TypePourcentage     `protobuf:"bytes,4,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MessageIaReponse) Reset() {
	*x = MessageIaReponse{}
	mi := &file_rag_analyseIa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageIaReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageIaReponse) ProtoMessage() {}

func (x *MessageIaReponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_analyseIa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageIaReponse.ProtoReflect.Descriptor instead.
func (*MessageIaReponse) Descriptor() ([]byte, []int) {
	return file_rag_analyseIa_proto_rawDescGZIP(), []int{2}
}

func (x *MessageIaReponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageIaReponse) GetSousEntendu() bool {
	if x != nil {
		return x.SousEntendu
	}
	return false
}

func (x *MessageIaReponse) GetPourcentageSousEntendu() int32 {
	if x != nil {
		return x.PourcentageSousEntendu
	}
	return 0
}

func (x *MessageIaReponse) GetTypes() []*TypePourcentage {
	if x != nil {
		return x.Types
	}
	return nil
}

type AnalyseIaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Messages      []*MessageIa           `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyseIaRequest) Reset() {
	*x = AnalyseIaRequest{}
	mi := &file_rag_analyseIa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyseIaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseIaRequest) ProtoMessage() {}

func (x *AnalyseIaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_analyseIa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseIaRequest.ProtoReflect.Descriptor instead.
func (*AnalyseIaRequest) Descriptor() ([]byte, []int) {
	return file_rag_analyseIa_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyseIaRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AnalyseIaRequest) GetMessages() []*MessageIa {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ClassementItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Valeur        int32                  `protobuf:"varint,2,opt,name=valeur,proto3" json:"valeur,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassementItem) Reset() {
	*x = ClassementItem{}
	mi := &file_rag_analyseIa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassementItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassementItem) ProtoMessage() {}

func (x *ClassementItem) ProtoReflect() protoreflect.Message {
	mi := &file_rag_analyseIa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassementItem.ProtoReflect.Descriptor instead.
func (*ClassementItem) Descriptor() ([]byte, []int) {
	return file_rag_analyseIa_proto_rawDescGZIP(), []int{4}
}

func (x *ClassementItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClassementItem) GetValeur() int32 {
	if x != nil {
		return x.Valeur
	}
	return 0
}

type AnalyseIaResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AnalyseMessages []*MessageIaReponse    `protobuf:"bytes,1,rep,name=analyse_messages,json=analyseMessages,proto3" json:"analyse_messages,omitempty"`
	Classement      []*ClassementItem      `protobuf:"bytes,2,rep,name=classement,proto3" json:"classement,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyseIaResponse) Reset() {
	*x = AnalyseIaResponse{}
	mi := &file_rag_analyseIa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyseIaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseIaResponse) ProtoMessage() {}

func (x *AnalyseIaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_analyseIa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseIaResponse.ProtoReflect.Descriptor instead.
func (*AnalyseIaResponse) Descriptor() ([]byte, []int) {
	return file_rag_analyseIa_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyseIaResponse) GetAnalyseMessages() []*MessageIaReponse {
	if x != nil {
		return x.AnalyseMessages
	}
	return nil
}

func (x *AnalyseIaResponse) GetClassement() []*ClassementItem {
	if x != nil {
		return x.Classement
	}
	return nil
}

var File_rag_analyseIa_proto protoreflect.FileDescriptor

const file_rag_analyseIa_proto_rawDesc = "" +
	"\n" +
	"\x13rag/analyseIa.proto\x12\x03rag\"5\n" +
	"\tMessageIa\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"G\n" +
	"\x0fTypePourcentage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vpourcentage\x18\x02 \x01(\x05R\vpourcentage\"\xa8\x01\n" +
	"\x10MessageIaReponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vsousEntendu\x18\x02 \x01(\bR\vsousEntendu\x126\n" +
	"\x16pourcentageSousEntendu\x18\x03 \x01(\x05R\x16pourcentageSousEntendu\x12*\n" +
	"\x05types\x18\x04 \x03(\v2\x14.rag.TypePourcentageR\x05types\"T\n" +
	"\x10AnalyseIaRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12*\n" +
	"\bmessages\x18\x02 \x03(\v2\x0e.rag.MessageIaR\bmessages\"<\n" +
	"\x0eClassementItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06valeur\x18\x02 \x01(\x05R\x06valeur\"\x8a\x01\n" +
	"\x11AnalyseIaResponse\x12@\n" +
	"\x10analyse_messages\x18\x01 \x03(\v2\x15.rag.MessageIaReponseR\x0fanalyseMessages\x123\n" +
	"\n" +
	"classement\x18\x02 \x03(\v2\x13.rag.ClassementItemR\n" +
	"classement2G\n" +
	"\tAnalyseIa\x12:\n" +
	"\tAnalyseIa\x12\x15.rag.AnalyseIaRequest\x1a\x16.rag.AnalyseIaResponseB\x17Z\x15gateway-ctn/proto/ragb\x06proto3"

var (
	file_rag_analyseIa_proto_rawDescOnce sync.Once
	file_rag_analyseIa_proto_rawDescData []byte
)

func file_rag_analyseIa_proto_rawDescGZIP() []byte {
	file_rag_analyseIa_proto_rawDescOnce.Do(func() {
		file_rag_analyseIa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_analyseIa_proto_rawDesc), len(file_rag_analyseIa_proto_rawDesc)))
	})
	return file_rag_analyseIa_proto_rawDescData
}

var file_rag_analyseIa_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rag_analyseIa_proto_goTypes = []any{
	(*MessageIa)(nil),         // 0: rag.MessageIa
	(*TypePourcentage)(nil),   // 1: rag.TypePourcentage
	(*MessageIaReponse)(nil),  // 2: rag.MessageIaReponse
	(*AnalyseIaRequest)(nil),  // 3: rag.AnalyseIaRequest
	(*ClassementItem)(nil),    // 4: rag.ClassementItem
	(*AnalyseIaResponse)(nil), // 5: rag.AnalyseIaResponse
}
var file_rag_analyseIa_proto_depIdxs = []int32{
	1, // 0: rag.MessageIaReponse.types:type_name -> rag.TypePourcentage
	0, // 1: rag.AnalyseIaRequest.messages:type_name -> rag.MessageIa
	2, // 2: rag.AnalyseIaResponse.analyse_messages:type_name -> rag.MessageIaReponse
	4, // 3: rag.AnalyseIaResponse.classement:type_name -> rag.ClassementItem
	3, // 4: rag.AnalyseIa.AnalyseIa:input_type -> rag.AnalyseIaRequest
	5, // 5: rag.AnalyseIa.AnalyseIa:output_type -> rag.AnalyseIaResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rag_analyseIa_proto_init() }
func file_rag_analyseIa_proto_init() {
	if File_rag_analyseIa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_analyseIa_proto_rawDesc), len(file_rag_analyseIa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_analyseIa_proto_goTypes,
		DependencyIndexes: file_rag_analyseIa_proto_depIdxs,
		MessageInfos:      file_rag_analyseIa_proto_msgTypes,
	}.Build()
	File_rag_analyseIa_proto = out.File
	file_rag_analyseIa_proto_goTypes = nil
	file_rag_analyseIa_proto_depIdxs = nil
}
