// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rag/poserQuestion.proto

package rag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_rag_poserQuestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rag_poserQuestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rag_poserQuestion_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PoserQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"` // <- nouvelle question ajoutée
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoserQuestionRequest) Reset() {
	*x = PoserQuestionRequest{}
	mi := &file_rag_poserQuestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoserQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoserQuestionRequest) ProtoMessage() {}

func (x *PoserQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_poserQuestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoserQuestionRequest.ProtoReflect.Descriptor instead.
func (*PoserQuestionRequest) Descriptor() ([]byte, []int) {
	return file_rag_poserQuestion_proto_rawDescGZIP(), []int{1}
}

func (x *PoserQuestionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PoserQuestionRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *PoserQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type PoserQuestionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RetrievedMessages []*Message             `protobuf:"bytes,1,rep,name=retrieved_messages,json=retrievedMessages,proto3" json:"retrieved_messages,omitempty"`
	Reply             string                 `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PoserQuestionResponse) Reset() {
	*x = PoserQuestionResponse{}
	mi := &file_rag_poserQuestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoserQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoserQuestionResponse) ProtoMessage() {}

func (x *PoserQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_poserQuestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoserQuestionResponse.ProtoReflect.Descriptor instead.
func (*PoserQuestionResponse) Descriptor() ([]byte, []int) {
	return file_rag_poserQuestion_proto_rawDescGZIP(), []int{2}
}

func (x *PoserQuestionResponse) GetRetrievedMessages() []*Message {
	if x != nil {
		return x.RetrievedMessages
	}
	return nil
}

func (x *PoserQuestionResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_rag_poserQuestion_proto protoreflect.FileDescriptor

const file_rag_poserQuestion_proto_rawDesc = "" +
	"\n" +
	"\x17rag/poserQuestion.proto\x12\x03rag\"3\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"r\n" +
	"\x14PoserQuestionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12(\n" +
	"\bmessages\x18\x02 \x03(\v2\f.rag.MessageR\bmessages\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\"j\n" +
	"\x15PoserQuestionResponse\x12;\n" +
	"\x12retrieved_messages\x18\x01 \x03(\v2\f.rag.MessageR\x11retrievedMessages\x12\x14\n" +
	"\x05reply\x18\x02 \x01(\tR\x05reply2V\n" +
	"\fTokenService\x12F\n" +
	"\rPoserQuestion\x12\x19.rag.PoserQuestionRequest\x1a\x1a.rag.PoserQuestionResponseB\x17Z\x15gateway-ctn/proto/ragb\x06proto3"

var (
	file_rag_poserQuestion_proto_rawDescOnce sync.Once
	file_rag_poserQuestion_proto_rawDescData []byte
)

func file_rag_poserQuestion_proto_rawDescGZIP() []byte {
	file_rag_poserQuestion_proto_rawDescOnce.Do(func() {
		file_rag_poserQuestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_poserQuestion_proto_rawDesc), len(file_rag_poserQuestion_proto_rawDesc)))
	})
	return file_rag_poserQuestion_proto_rawDescData
}

var file_rag_poserQuestion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rag_poserQuestion_proto_goTypes = []any{
	(*Message)(nil),               // 0: rag.Message
	(*PoserQuestionRequest)(nil),  // 1: rag.PoserQuestionRequest
	(*PoserQuestionResponse)(nil), // 2: rag.PoserQuestionResponse
}
var file_rag_poserQuestion_proto_depIdxs = []int32{
	0, // 0: rag.PoserQuestionRequest.messages:type_name -> rag.Message
	0, // 1: rag.PoserQuestionResponse.retrieved_messages:type_name -> rag.Message
	1, // 2: rag.TokenService.PoserQuestion:input_type -> rag.PoserQuestionRequest
	2, // 3: rag.TokenService.PoserQuestion:output_type -> rag.PoserQuestionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rag_poserQuestion_proto_init() }
func file_rag_poserQuestion_proto_init() {
	if File_rag_poserQuestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_poserQuestion_proto_rawDesc), len(file_rag_poserQuestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_poserQuestion_proto_goTypes,
		DependencyIndexes: file_rag_poserQuestion_proto_depIdxs,
		MessageInfos:      file_rag_poserQuestion_proto_msgTypes,
	}.Build()
	File_rag_poserQuestion_proto = out.File
	file_rag_poserQuestion_proto_goTypes = nil
	file_rag_poserQuestion_proto_depIdxs = nil
}
