// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/autorisation.proto

package autorisation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutorisationService_VerifieEtIncrementeToken_FullMethodName = "/autorisation.AutorisationService/VerifieEtIncrementeToken"
)

// AutorisationServiceClient is the client API for AutorisationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutorisationServiceClient interface {
	VerifieEtIncrementeToken(ctx context.Context, in *VerifieTokenRequest, opts ...grpc.CallOption) (*VerifieTokenReponse, error)
}

type autorisationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutorisationServiceClient(cc grpc.ClientConnInterface) AutorisationServiceClient {
	return &autorisationServiceClient{cc}
}

func (c *autorisationServiceClient) VerifieEtIncrementeToken(ctx context.Context, in *VerifieTokenRequest, opts ...grpc.CallOption) (*VerifieTokenReponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifieTokenReponse)
	err := c.cc.Invoke(ctx, AutorisationService_VerifieEtIncrementeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutorisationServiceServer is the server API for AutorisationService service.
// All implementations must embed UnimplementedAutorisationServiceServer
// for forward compatibility.
type AutorisationServiceServer interface {
	VerifieEtIncrementeToken(context.Context, *VerifieTokenRequest) (*VerifieTokenReponse, error)
	mustEmbedUnimplementedAutorisationServiceServer()
}

// UnimplementedAutorisationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutorisationServiceServer struct{}

func (UnimplementedAutorisationServiceServer) VerifieEtIncrementeToken(context.Context, *VerifieTokenRequest) (*VerifieTokenReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifieEtIncrementeToken not implemented")
}
func (UnimplementedAutorisationServiceServer) mustEmbedUnimplementedAutorisationServiceServer() {}
func (UnimplementedAutorisationServiceServer) testEmbeddedByValue()                             {}

// UnsafeAutorisationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutorisationServiceServer will
// result in compilation errors.
type UnsafeAutorisationServiceServer interface {
	mustEmbedUnimplementedAutorisationServiceServer()
}

func RegisterAutorisationServiceServer(s grpc.ServiceRegistrar, srv AutorisationServiceServer) {
	// If the following call pancis, it indicates UnimplementedAutorisationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutorisationService_ServiceDesc, srv)
}

func _AutorisationService_VerifieEtIncrementeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifieTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutorisationServiceServer).VerifieEtIncrementeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutorisationService_VerifieEtIncrementeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutorisationServiceServer).VerifieEtIncrementeToken(ctx, req.(*VerifieTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutorisationService_ServiceDesc is the grpc.ServiceDesc for AutorisationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutorisationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "autorisation.AutorisationService",
	HandlerType: (*AutorisationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifieEtIncrementeToken",
			Handler:    _AutorisationService_VerifieEtIncrementeToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/autorisation.proto",
}
