# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/poserQuestion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/poserQuestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/poserQuestion.proto\x12\x03rag\"&\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"W\n\x14PoserQuestionRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x1e\n\x08messages\x18\x02 \x03(\x0b\x32\x0c.rag.Message\x12\x10\n\x08question\x18\x03 \x01(\t\"P\n\x15PoserQuestionResponse\x12(\n\x12retrieved_messages\x18\x01 \x03(\x0b\x32\x0c.rag.Message\x12\r\n\x05reply\x18\x02 \x01(\t2V\n\x0cTokenService\x12\x46\n\rPoserQuestion\x12\x19.rag.PoserQuestionRequest\x1a\x1a.rag.PoserQuestionResponseB\x17Z\x15gateway-ctn/proto/ragb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.poserQuestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025gateway-ctn/proto/rag'
  _globals['_MESSAGE']._serialized_start=34
  _globals['_MESSAGE']._serialized_end=72
  _globals['_POSERQUESTIONREQUEST']._serialized_start=74
  _globals['_POSERQUESTIONREQUEST']._serialized_end=161
  _globals['_POSERQUESTIONRESPONSE']._serialized_start=163
  _globals['_POSERQUESTIONRESPONSE']._serialized_end=243
  _globals['_TOKENSERVICE']._serialized_start=245
  _globals['_TOKENSERVICE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
